INSERT INTO "DERBY"."UTILISATEURS" (DERNIERE_MISE_A_JOUR,EMAIL,MODIFIER_PAR,NOM,PASSWORD,PRENOM) VALUES (CURRENT_TIMESTAMP,'soufian.a@free.fr','soufian AIT TIRITE','AIT TIRITE','test','SOUFIAN');
INSERT INTO "DERBY"."UTILISATEURS" (DERNIERE_MISE_A_JOUR,EMAIL,MODIFIER_PAR,NOM,PASSWORD,PRENOM) VALUES (CURRENT_TIMESTAMP,'dubois@blabla.fr','soufian AIT TIRITE','DUBOIS','dubois11','MANUEL');
INSERT INTO "DERBY"."UTILISATEURS" (DERNIERE_MISE_A_JOUR,EMAIL,MODIFIER_PAR,NOM,PASSWORD,PRENOM) VALUES (CURRENT_TIMESTAMP,'dupontc@blabla.fr','soufian AIT TIRITE','DUPONT','dupont00','CHRISTOPHE');
INSERT INTO "DERBY"."UTILISATEURS" (DERNIERE_MISE_A_JOUR,EMAIL,MODIFIER_PAR,NOM,PASSWORD,PRENOM) VALUES (CURRENT_TIMESTAMP,'deschamps@blabla.fr','soufian AIT TIRITE','DESCHAMPS','didier22','DIDIER');

