INSERT INTO "DERBY"."ACTION" (ACTION,DERNIERE_MISE_A_JOUR,DESCRIPTION,MODIFIER_PAR) VALUES ('Rédiger une annonce',CURRENT_TIMESTAMP,'droit de rédaction','Soufian AIT TIRITE');
INSERT INTO "DERBY"."ACTION" (ACTION,DERNIERE_MISE_A_JOUR,DESCRIPTION,MODIFIER_PAR) VALUES ('Modifier une annonce',CURRENT_TIMESTAMP,'droit de modification','Soufian AIT TIRITE');
INSERT INTO "DERBY"."ACTION" (ACTION,DERNIERE_MISE_A_JOUR,DESCRIPTION,MODIFIER_PAR) VALUES ('Supprimer une annonce',CURRENT_TIMESTAMP,'droit de suppression','Soufian AIT TIRITE');
INSERT INTO "DERBY"."ACTION" (ACTION,DERNIERE_MISE_A_JOUR,DESCRIPTION,MODIFIER_PAR) VALUES ('Publier une annonce',CURRENT_TIMESTAMP,'droit de publication','Soufian AIT TIRITE');
INSERT INTO "DERBY"."ACTION" (ACTION,DERNIERE_MISE_A_JOUR,DESCRIPTION,MODIFIER_PAR) VALUES ('Vendre une guitare',CURRENT_TIMESTAMP,'droit de vendre une guitare','Soufian AIT TIRITE');
INSERT INTO "DERBY"."ACTION" (ACTION,DERNIERE_MISE_A_JOUR,DESCRIPTION,MODIFIER_PAR) VALUES ('Gérer les accès',CURRENT_TIMESTAMP,'droit de gérer les accès','Soufian AIT TIRITE');
INSERT INTO "DERBY"."ACTION" (ACTION,DERNIERE_MISE_A_JOUR,DESCRIPTION,MODIFIER_PAR) VALUES ('Gérer les magasins',CURRENT_TIMESTAMP,'droit de gérer les magasin','Soufian AIT TIRITE');
INSERT INTO "DERBY"."ACTION" (ACTION,DERNIERE_MISE_A_JOUR,DESCRIPTION,MODIFIER_PAR) VALUES ('Consulter les indicateurs',CURRENT_TIMESTAMP,'droit de consulter les indicateurs','Soufian AIT TIRITE');
