INSERT INTO "DERBY"."ROLES_UTILISATEURS" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ROLES_FK,UTLISATEURS_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',1,1);
INSERT INTO "DERBY"."ROLES_UTILISATEURS" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ROLES_FK,UTLISATEURS_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',1,4);
INSERT INTO "DERBY"."ROLES_UTILISATEURS" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ROLES_FK,UTLISATEURS_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',2,2);
INSERT INTO "DERBY"."ROLES_UTILISATEURS" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ROLES_FK,UTLISATEURS_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',3,3);
INSERT INTO "DERBY"."ROLES_UTILISATEURS" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ROLES_FK,UTLISATEURS_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',3,4);

