INSERT INTO "DERBY"."UTILISATEUR" (DERNIERE_MISE_A_JOUR,EMAIL,MODIFIE_PAR,NOM,PASSWORD,PRENOM,ROLE_FK) VALUES (CURRENT_TIMESTAMP,'pierre.dupont@free.fr','Soufian AIT TIRITE','Dupont','pidup2016','Pierre',1);

