
CREATE TABLE ACTION (ida integer primary key GENERATED ALWAYS AS IDENTITY, action varchar(255), DERNIERE_MISE_A_JOUR TIMESTAMP, description varchar(255), modifier_par varchar(255));
CREATE TABLE ROLES (IDR integer primary key GENERATED ALWAYS AS IDENTITY, DERNIERE_MISE_A_JOUR TIMESTAMP, DESCRIPTION varchar(255), MODIFIER_PAR varchar(255), ROLE varchar(255));
CREATE TABLE UTILISATEURS (IDUT integer primary key GENERATED ALWAYS AS IDENTITY, DERNIERE_MISE_A_JOUR TIMESTAMP, EMAIL varchar(255), MODIFIER_PAR varchar(255), NOM varchar(255), PASSWORD varchar(255), PRENOM varchar(255));
CREATE TABLE ROLES_ACTION (IDRA integer primary key GENERATED ALWAYS AS IDENTITY, DERNIERE_MISE_A_JOUR TIMESTAMP, MODIFIER_PAR varchar(255), ACTION_FK integer references ACTION(IDA), ROLE_FK integer references ROLES(IDR));
CREATE TABLE ROLES_UTILISATEURS (IDRU integer primary key GENERATED ALWAYS AS IDENTITY, DERNIERE_MISE_A_JOUR timestamp, MODIFIER_PAR VARCHAR(255), ROLES_FK integer references ROLES(IDR), UTILISATEURS_FK integer references UTILISATEURS(IDUT));


