INSERT INTO "DERBY"."ROLES_ACTION" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ACTION_FK,ROLE_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',7,1);
INSERT INTO "DERBY"."ROLES_ACTION" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ACTION_FK,ROLE_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',6,1);
INSERT INTO "DERBY"."ROLES_ACTION" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ACTION_FK,ROLE_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',8,1);
INSERT INTO "DERBY"."ROLES_ACTION" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ACTION_FK,ROLE_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',1,2);
INSERT INTO "DERBY"."ROLES_ACTION" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ACTION_FK,ROLE_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',2,2);
INSERT INTO "DERBY"."ROLES_ACTION" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ACTION_FK,ROLE_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',3,2);
INSERT INTO "DERBY"."ROLES_ACTION" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ACTION_FK,ROLE_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',4,2);
INSERT INTO "DERBY"."ROLES_ACTION" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ACTION_FK,ROLE_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',5,2);
INSERT INTO "DERBY"."ROLES_ACTION" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ACTION_FK,ROLE_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',1,3);
INSERT INTO "DERBY"."ROLES_ACTION" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ACTION_FK,ROLE_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',2,3);
INSERT INTO "DERBY"."ROLES_ACTION" (DERNIERE_MISE_A_JOUR,MODIFIER_PAR,ACTION_FK,ROLE_FK) VALUES (CURRENT_TIMESTAMP,'AIT TIRITE SOUFIAN',3,3);

